// categories.jsx
const categories = [
    {
        id: 1,
        name: "Skin Care",
        slug: "skin-care",
        image: "/images/categories/01.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 110,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 111,
                name: "Cleansers",
                slug: "cleansers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 112,
                name: "Cleansers",
                slug: "cleansers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 113,
                name: "Serum",
                slug: "serum",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 114,
                name: "Masks",
                slug: "masks",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 115,
                name: "Sun care",
                slug: "sun-care",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 116,
                name: "Skin Tech Tools",
                slug: "skin-tech-tools",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 117,
                name: "Trending",
                slug: "trending",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
        ]
    },
    {
        id: 2,
        name: "Hair Care",
        slug: "hair-care",
        image: "/images/categories/02.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 211,
                name: "Shampoo & Conditioner",
                slug: "shampoo-conditioner",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 212,
                name: "Hair Nourishment",
                slug: "hair-nourishment",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 213,
                name: "Hair Styling",
                slug: "hair-styling",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 214,
                name: "Hair Brushes & Accessories",
                slug: "hair-brushes-accessories",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 215,
                name: "Hair Styling Devices",
                slug: "hair-styling-devices",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 216,
                name: "Hair Coloring",
                slug: "hair-coloring",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 217,
                name: "Salon Hair Care",
                slug: "salon-hair-care",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 218,
                name: "Hair & Scalp Treatment",
                slug: "hair-scalp-treatment",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            },
            {
                id: 219,
                name: "Professional Hair Care",
                slug: "professional-hair-care",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 3,
        name: "Makeup",
        slug: "makeup",
        image: "/images/categories/03.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 311,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 4,
        name: "Last Chance Offers",
        slug: "last-chance-offers",
        image: "/images/categories/04.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 411,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 5,
        name: "Global Products",
        slug: "global-products",
        image: "/images/categories/05.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 511,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 6,
        name: "Mom & Baby",
        slug: "mom-baby",
        image: "/images/categories/06.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 611,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 7,
        name: "Diapers",
        slug: "diapers",
        image: "/images/categories/07.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 711,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 8,
        name: "Treatments",
        slug: "treatments",
        image: "/images/categories/08.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 811,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 9,
        name: "Daily Essentials",
        slug: "daily-essentials",
        image: "/images/categories/09.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 911,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 10,
        name: "Healthy Food",
        slug: "healthy-food",
        image: "/images/categories/10.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 1011,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 11,
        name: "Vitamins",
        slug: "vitamins",
        image: "/images/categories/11.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 1111,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
    {
        id: 12,
        name: "Health Care",
        slug: "health-care",
        image: "/images/categories/12.webp",
        href: "/category",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        productsCount: 120,
        featured: true,
        subcategories: [
            {
                id: 2111,
                name: "Moisturizers",
                slug: "moisturizers",
                image: "path/to/moisturizers-image.jpg",
                title: "Top Moisturizers",
                description: "Hydrate your skin with our top moisturizers.",
                productsCount: 50,
                featured: true,
            }
        ]
    },
];

export default categories;
