// brandsData.jsx
const brandsData = [
    {
        id: 1,
        name: "Isis Pharma",
        slug: "isispharma",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand01.webp",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    },
    {
        id: 2,
        name: "Niviea",
        slug: "nivea",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand02.webp",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    },
    {
        id: 3,
        name: "Skin Cenuticals",
        slug: "skin-cenuticals",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand03.webp",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    },
    {
        id: 4,
        name: "Water Wipes",
        slug: "water-wipes",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand04.webp",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    },
    {
        id: 5,
        name: "Mustela",
        slug: "mustela",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand05.webp",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    },
    {
        id: 6,
        name: "SVR",
        slug: "svr",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand06.png",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    },
    {
        id: 7,
        name: "L'Oreal",
        slug: "loreal",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand07.webp",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    },
    {
        id: 8,
        name: "Pjur",
        slug: "pjur",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand08.webp",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    },
    {
        id: 9,
        name: "Priorin",
        slug: "priorin",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand09.png",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    },
    {
        id: 10,
        name: "Kerastase",
        slug: "kerastase",
        href: "/brands/",
        title: "Best Skin Care Products",
        description: "Explore our range of skin care products for all skin types.",
        logo: "/images/brands/brand10.webp",
        banners: [
            { id: 1, image: '/images/sections/spen01.webp' },
            { id: 2, image: '/images/sections/spen02.webp' },
            { id: 3, image: '/images/sections/spen03.webp' },
            { id: 4, image: '/images/sections/spen04.webp' },
        ],
    }
];

export default brandsData;
